config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "articles#index"
  resources :articles do
    resources :likes, only: [:create, :destroy]
  end  
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  
  
  def user_liked(user_id)
   likes.where(user_id: user_id).exists?
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article, counter_cache: :like_count
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :articles, dependent: :destroy
  validates :username, presence: true
  validates :profile, length: { maximum: 150 }

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :username, :password, :password_confirmation, :image ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end  
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order(id: "DESC")
  end
  
  def new
    @article = Article.new
  end  
  
  def create
    Article.create(title: article_params[:title], text: article_params[:text], user_id: current_user.id)
  end  
  
  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to root_path
  end  
  
  def show
    @article = Article.find(params[:id])
  end  
  
  private
  def article_params
    params.require(:article).permit(:text,:title)
  end  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, article_id: params[:article_id])
    @article = Article.find(params[:article_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, article_id: params[:id])
    like.destroy
    @likes = Like.where(article_id: params[:id])
    @article = Article.find(params[:article_id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id]) if params[:id]
    @image = @user.image
    @username = @user.username
    @profile = @user.profile
    @articles = @user.articles
    @id = @user.id
  end
  
  def edit
    @user = User.find(params[:id]) if params[:id]
    @username = @user.username
    @image = @user.image
    @profile = @user.profile
  end
  
  def update
    current_user.update(user_params)
    redirect_to("/")
  end  
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to("/")
  end  
  
  def user_params
    params.require(:user).permit(:username, :profile, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def simple_time(time)
    time.strftime("%Y-%m-%d　%H:%M　")
  end 
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_like.html.erb
<% if user_signed_in? %>
  <% if article.user_liked(current_user.id) %>
    <%= link_to article_like_path(article, article_id: article.id), method: :delete, remote: true do %>
      <i class="fas fa-heart">
        <span>
          <%= article.like_count %>
        </span>
      </i>
    <% end %>
  <% else %>
    <%= link_to  article_likes_path(article), method: :post, remote: true do %>
      <span>
        <i class="far fa-heart">
          <%= article.like_count %>
        </i>
      </span>
    <% end %>
  <% end %>
<% else %>
  <%= link_to user_session_path do %>
    <i class="far fa-heart">
      <span>
          <%= article.like_count %>
      </span>
    </i>
  <% end %>  
<% end %>

app/views/articles/_list.html.erb
    <div class = "article-list">
        <div class = "article-list__article-user" >
            <% if article.user.image.present? %>
                <a href = "/users/<%= article.user.id %>"><%= image_tag article.user.image.url, class: "article-list__article-user__image" %></a>
            <% else %>
                <a href = "/users/<%= article.user.id %>"><%= image_tag 'no_image.png', class: "article-list__article-user__image" %></a>
            <% end %>  
        </div>
        <div class = "article-list__article-info">
            <div  class = "article-list__article-info__user">
                <%= article.user.username %><br/>
            </div>
            <div class= "article-list__article-info__title">
                 <%= link_to "#{article.title}", article_path(article.id) %>
            </div>    
        </div>
        <% if user_signed_in? %>
            <div class = "article-list__article-info__edit">
              <% if current_user.id == article.user.id %>
                <%= link_to "articles/#{article.id}", :method => :delete do %>
                  <i class="fa fa-trash-alt"></i>
                <% end %>
              <% end %>  
            </div>
        <% end %>
    </div> 

app/views/articles/create.html.erb
<p>記事が投稿されました</p>
<%= link_to "TOPへ", root_path%>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
    <%= render partial: "articles/list", locals: { article: article } %>
    <div id="like-<%= article.id %>">
        <%= render partial: "articles/like", locals: { article: article } %>
    </div>    
<% end %>    

app/views/articles/new.html.erb
<%= form_with(model: @article, local: true) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  
  <%= f.label :text %>
  <%= f.text_area :text %>
  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<div class = "datail-article">
  <div class = "datail-article__title">
    <%= @article.title %>
  </div>
  <div class = "datail-article__user">
    <% if @article.user.image.present? %>
        <a href = "/users/<%= @article.user.id %>"><%= image_tag @article.user.image.url, class: "datail-article__user__image" %></a>
    <% else %>
        <a href = "/users/<%= @article.user.id %>"><%= image_tag 'no_image.png', class: "datail-article__user__image" %></a>
    <% end %>  
    <%= @article.user.username %>さんが<%= simple_time(@article[:created_at] ) %>に投稿
  </div>
  <div class = "datail-article__text">
    <% text = @article.text %>
    <%= simple_format(text) %>
  </div>
  
  <!--<div class = "datil-article__share">-->
  <!--  <a href="https://twitter.com/share?-->
  <!--  via={@OurpostsO}&-->
  <!--  related={@OurpostsO}&-->
  <!--  hashtags=投稿アプリ,シェアしよう&-->
  <!--  text=#{@article.user}さんの記事「#{@article.title}」" -->
  <!--  rel="nofollow" -->
  <!--  target="_blank"><i class="fab fa-twitter-square"></i></a>-->
  <!--</div>-->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OURposts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel='stylesheet' href='https://unpkg.com/ress/dist/ress.min.css'>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@600&display=swap" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 

  <body>
    <div class="menu-list">
       <ul>
         <li><%= link_to "OURposts", root_path, class: "menu-list__title"%></li>
         <% if user_signed_in? %>
           <li><%= link_to "post",  new_article_path%></li>
           <li><%= link_to "#{current_user.username}さん",user_path(current_user), method: :get %> </li>
           <li><%= link_to "sign_out",destroy_user_session_path, method: :delete %> </li>
         <% else %>   
           <li><%= link_to "sign_up", new_user_registration_path %></li>
           <li><%= link_to "login", new_user_session_path %></li>
         <% end %>
       </ul>
    </div>
    <div class="main"> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/create.js.erb
$("#like-<%= @article.id %>").html("<%= j(render partial: 'articles/like', locals: {article: @article}) %>")

app/views/likes/destroy.js.erb
$("#like-<%= @article.id %>").html("<%= j(render partial: 'articles/like', locals: {article: @article}) %>")

app/views/users/edit.html.erb
<div class = "account-page">
  <%= form_for(current_user) do |f| %>
 
    <div class = "account-page__inner--icon">
      <% if @image.present? %>
        <%= image_tag "#{@image.url}",  class: 'account-page__inner--icon__image', width: '100%' %>
      <% else %>
        <%= image_tag "no_image.png",  class: 'account-page__inner--icon__image', width: '100%' %>
      <% end %>
    </div>
    
    <div class = "account-page__edit">
      <div class = "account-page__edit__username">
        <%= f.label :username %>
        <%= f.text_field :username, :placeholder => "#{@username}"%>
      </div>
      
      <div class = "account-page__edit__profile">
        <%= f.label :profile %>
        <%= f.text_area :profile %>      
      </div>
      
      <div class = "account-page__edit__file">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>
      
      <div class = "account-page__edit__update">
        <%= f.submit "update" %>
      </div>
    </div>  
  <% end %>
</div>

app/views/users/show.html.erb
<div class = "show-page">
  <div class = "show-page__inner--icon">
       <% if @image.present? %>
        <%= image_tag "#{@image.url}",  class: 'show-page__inner--icon__input__image', width: '100%' %>
      <% else %>
        <%= image_tag "no_image.png",  class: 'show-page__inner--icon__input__image', width: '100%' %>
      <% end %>
    </div>
    <div class = "show-page__inner--icon__profileall">
      <div class = "show-page__inner--icon__profileall__username">
        <% text = "#{@username}" %>
        <%= simple_format text %>
      </div>
      <div class = "show-page__inner--icon__profileall__profile">
        <% profile = "#{@profile}" %>
        <%= simple_format profile %>
        
      <% if current_user.id == @id %>  
        <div class = "show-page__buttons">
          <div class = "show-page__buttons__item">
            <%= link_to user_path(@id), :method => :delete do %>
              <i class="fa fa-trash-alt"></i>
            <% end %>
          </div>
          <div class = "show-page__buttons__item">
            <%= link_to edit_user_path(@id), :method => :get do %>
              <i class="fa fa-edit"></i>
            <% end %>          
          </div>
        </div>
      <% end %>  
      </div>
    </div>
</div>
<div class = "log">
    <% @articles.each do |article| %>
      <%= render partial: "articles/list", locals: { article: article } %>
    <% end %>  
</div>